#!/bin/bash -e

rm -rf ./dist/
yarn generate
rm -rf src/compiled/

mkdir -p src/compiled/

CONTRACTS="ProxyIdentity ProxyFactory HashcashDifficulty IForwarder IProxyDeployingPaymaster"

BUILDFOLDER=./build/contracts
OUTFOLDER=./src/compiled/
for c in $CONTRACTS; do
  echo copy $OUTFOLDER/$c.json
  cp $BUILDFOLDER/$c.json $OUTFOLDER
done

tsc
